#! /bin/bash
files=("Visual Studio Code" "IntelliJ IDEA" "eclipse" "IntelliJ IDEA CE" "Xcode" "Android")

menuitems() {
    echo "请选择创建IDE的快捷方式："
    for i in ${!files[@]}; do
        printf "%3d%s) %s\n" $((i+1)) "${choices[i]:- }" "${files[i]}"
    done
    [[ "$msg" ]] && echo "$msg"; :
}

prompt="请输入序号，多选请以空格隔开："
while menuitems && read -rp "$prompt" num && [[ "$num" ]]; do
    echo "输入：${num}"
    array=(${num// / })  
 
    for var in ${array[@]}
    do
    echo $var
    done 
    exit
    # [[ "$num" != *[![:digit:]]* ]] && (( num > 0 && num <= ${#files[@]} )) || {
    #     msg="Invalid option: $num"; continue
    # }
    # if [ $num == ${#files[@]} ];then
    #   exit
    # fi
    # ((num--)); msg="${files[num]} was ${choices[num]:+un-}selected"
    # [[ "${choices[num]}" ]] && choices[num]="" || choices[num]="x"
done

# printf "You selected"; msg=" nothing"
# for i in ${!files[@]}; do
#     [[ "${choices[i]}" ]] && { printf " %s" "${files[i]}"; msg=""; }
# done
# echo "$msg"